import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/javascript/": [
    "/javascript/",
    "/javascript/precompile.md",
    "/javascript/async.md",
    "/javascript/currying.md",
    "/javascript/memory.leak.md",
    "/javascript/deep.clone.md",
    "/javascript/prototype.md",
    "/javascript/debounce.throttle.md",
    "/javascript/running.md",
    "/javascript/event.loop.md",
    "/javascript/module.md",
    "/javascript/call.apply.bind.md",
    "/javascript/new.md",
    "/javascript/this.md",
    "/javascript/oop.md",
    "/javascript/parseInt.parseFloat.md",
    "/javascript/reg-exp.md",
    "/javascript/es6.md",
    "/javascript/deweight.array.md",
    "/javascript/questions.md",
  ],
  "/typescript/": ["/typescript/", "/typescript/cmd.md", "/typescript/infer.md", "/typescript/satisfies-as.md"],
  "/node/": ["/node/", "/node/jwt.md", "/node/json.md"],
  "/performance": [
    "/performance",
    "/performance/开篇.md",
    "/performance/webpack性能调优与Gzip原理.md",
    "/performance/图片优化之质量与性能的博弈.md",
    "/performance/览器缓存机制介绍与缓存策略剖析.md",
    "/performance/从Cookie到WebStorage、IndexDB.md",
    "/performance/服务端渲染的探索与实践.md",
    "/performance/解锁浏览器背后的运行机制.md",
    "/performance/DOM优化原理与基本实践.md",
    "/performance/EventLoop与异步更新策略.md",
    "/performance/回流（Reflow）与重绘（Repaint）.md",
    "/performance/优化首屏体验Lazy-Load初探.md",
    "/performance/事件的节流（throttle）与防抖（debounce）.md",
    "/performance/Performance、LightHouse与性能API.md",
    "/performance/CDN的缓存与回源机制解析.md",
  ],
  "/webpack/": ["/webpack/", "/webpack/asset.management.md", "/webpack/output.management.md", "/webpack/development.md", "/webpack/code.splitting.md", "/webpack/hmr.md", "/webpack/tree.shaking.md"],
});
