import { sidebar } from "vuepress-theme-hope";

const js = [
  "/js/",
  "/js/introduction.md",
  "/js/variables.md",
  "/js/data-types.md",
  "/js/equality.md",
  "/js/expressions-control-flow.md",
  "/js/parseInt.parseFloat.md",
  "/js/strict-mode.md",
  "/js/precompile.md",
  "/js/running.md",
  "/js/this.md",
  "/js/prototype.md",
  "/js/new.md",
  "/js/memory.leak.md",
  "/js/functions.md",
  "/js/call.apply.bind.md",
  "/js/oop.md",
  "/js/currying.md",
  "/js/higher-order-function.md",
  "/js/lazy-function.md",
  "/js/iterators-generators.md",
  "/js/async.md",
  "/js/event.loop.md",
  "/js/api.md",
  "/js/dom-api.md",
  "/js/web-worker.md",
  "/js/browser-devtools.md",
  "/js/debounce.throttle.md",
  "/js/time.chunk.md",
  "/js/module.md",
  "/js/deep.clone.md",
  "/js/array.md",
  "/js/deweight.array.md",
  "/js/reg-exp.md",
  "/js/es6.md",
  "/js/questions.md",
];

const ts = [
  "/ts/",
  "/ts/introduction.md",
  "/ts/cmd.md",
  "/ts/tsconfig.md",
  "/ts/type-basics.md",
  "/ts/type-inference-compatibility.md",
  "/ts/type-narrowing.md",
  "/ts/interfaces.md",
  "/ts/functions.md",
  "/ts/classes.md",
  "/ts/generics.md",
  "/ts/infer.md",
  "/ts/utility-types.md",
  "/ts/advanced-types.md",
  "/ts/satisfies-as.md",
  "/ts/modules-namespaces.md",
  "/ts/decorators.md",
  "/ts/ecosystem.md",
];

const performance = [
  "/performance/开篇.md",
  "/performance/webpack性能调优与Gzip原理.md",
  "/performance/图片优化之质量与性能的博弈.md",
  "/performance/览器缓存机制介绍与缓存策略剖析.md",
  "/performance/从Cookie到WebStorage、IndexDB.md",
  "/performance/服务端渲染的探索与实践.md",
  "/performance/解锁浏览器背后的运行机制.md",
  "/performance/DOM优化原理与基本实践.md",
  "/performance/EventLoop与异步更新策略.md",
  "/performance/回流（Reflow）与重绘（Repaint）.md",
  "/performance/优化首屏体验Lazy-Load初探.md",
  "/performance/事件的节流（throttle）与防抖（debounce）.md",
  "/performance/Performance、LightHouse与性能API.md",
  "/performance/CDN的缓存与回源机制解析.md",
];

const webpack = ["/webpack/asset.management.md", "/webpack/output.management.md", "/webpack/development.md", "/webpack/code.splitting.md", "/webpack/hmr.md", "/webpack/tree.shaking.md"];

const nodejs = [
  "/node/",
  "/node/introduction.md",
  "/node/execute.md",
  "/node/nvm.md",
  "/node/npm.md",
  "/node/modules.md",
  "/node/async-programming.md",
  "/node/error-handling.md",
  "/node/environment-cli.md",
  "/node/files-paths.md",
  "/node/json.md",
  "/node/api-development.md",
  "/node/jwt.md",
  "/node/template-engines.md",
  "/node/databases.md",
  "/node/testing.md",
  "/node/logging.md",
  "/node/process-management.md",
  "/node/streams.md",
  "/node/threads-processes.md",
  "/node/debugging-performance.md",
];

const git = ["/git/git-reset.md", "/git/git-stash.md", "/git/git-remote.md"];

const ai = [
  "/ai/",
  "/ai/coding-workflow.md",
  "/ai/prompt-patterns.md",
  "/ai/cursor.md",
];

export default sidebar({
  "/js/": js,
  "/ts/": ts,
  "/node/": nodejs,
  "/performance": performance,
  "/webpack/": webpack,
  "/git/": git,
  "/ai/": ai,
});
